Jack add chart maker
e61-Institute/theme61 pull request #18
Opened 2022-11-04 02:24 UTC by JackBuckley

## Describe your changes

## Do the following before requesting a review

- [ ] I have written tests covering functions I have added or changed.
- [ ] I have run tests and they all pass.
- [ ] I have updated the package documentation with `devtools::document()`.
- [ ] I have updated the package website with `pkgdown::build_site_github_pages()`

2022-11-14 22:18 UTC, elyse-22 approved these changes

2022-11-14 22:35 UTC, aaronw22 requested changes
Just need to tick off the things in the PR checklist and comments.

Would you also be able to try the deprecated functions and the renamed functions and see if they produce the appropriate warnings.

2022-11-14 22:35 UTC, aaronw22 commented on R/e61_chart_maker.R
> +e61_chart_maker <-
New functions need to be added to the `_pkgdown.yml` (which I've done for you this time).

2022-11-14 22:35 UTC, aaronw22 commented on R/theme61.R
> +theme_e61_clean <- function(
New functions need to be added to the `_pkgdown.yml` (which I've done for you this time).

2022-11-14 22:35 UTC, aaronw22 commented on NEWS.md
> +* *Jack please add your changes here.*
@JackBuckley please add your changes to the news file

2022-11-18 03:21 UTC, elyse-22 approved these changes

2022-12-09 03:43 UTC, aaronw22 approved these changes

2022-12-09 03:44 UTC, merged